# Generated by Django 6.0 on 2025-12-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jolly', '0002_alter_cartitem_food_image_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
