# Generated by Django 6.0 on 2025-12-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jolly', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('LOGIN_FAIL', 'Failed Login Attempt'), ('SENSITIVE_ACCESS', 'Sensitive Data Access'), ('BREAKAGE', 'Backend Error (500)'), ('DATA_VOL', 'High Data Usage')], max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('path', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('severity', models.IntegerField(default=1)),
            ],
        ),
    ]
