# Generated by Django 6.0 on 2025-12-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jolly', '0005_securitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='address_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
