# Generated by Django 6.0 on 2026-01-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jolly', '0008_delivery_customer_delivery_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
