# Generated by Django 6.0 on 2026-01-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jolly', '0009_delivery_landmark_delivery_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
