# Generated by Django 6.0 on 2026-01-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jolly', '0010_delivery_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='token',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
