# Generated by Django 6.0 on 2026-01-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jolly', '0011_delivery_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='items_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
