# Generated by Django 6.0 on 2026-01-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jolly', '0012_delivery_items_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(default=0, help_text="Driver's contact number", max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_plate',
            field=models.CharField(default=0, help_text='e.g., AS-202-26', max_length=20),
            preserve_default=False,
        ),
    ]
