# Generated by Django 6.0 on 2026-01-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jolly', '0013_driver_phone_number_driver_vehicle_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='priority_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='current_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='driver',
            name='current_lng',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Is the driver ready for new jobs?'),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_location_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('new', 'New (Searching Driver)'), ('assigned', 'Driver Assigned'), ('picked', 'Picked'), ('delivered', 'Delivered')], default='new', max_length=20),
        ),
    ]
